version: "3.1"
services:
  server:
    image: yandex/clickhouse-server
    ports:
      - "8123:8123"
      - "9000:9000"
      - "9009:9009"
    environment:
      CLICKHOUSE_DB: audit
      CLICKHOUSE_USER: user
      CLICKHOUSE_PASSWORD: 123
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  client:
    image: yandex/clickhouse-client
    command: ['--host', 'server']